%%CAPTURE_QUADRATURE_1D Capture oracle fixtures for the 1-D quadrature
% builders:
%   ClenshawCurtisPoints1D -> ...numerical_integration.clenshaw_curtis_points_1d
%   FejerPoints1D          -> ...numerical_integration.fejer_points_1d
%   conformMapQuadPts1D    -> ...numerical_integration.conform_map_quad_pts_1d
% MATLAB TCL tree at commit a9acd8f. n values chosen to exercise both the
% computed path and (n=64, where mod(2048,n)==0) the pretabulated path of
% ClenshawCurtisPoints1D, which per its comments was generated by the same
% algorithm. CSV rows: [tag params..., xi..., w...] transposed so the
% Python test reads 1-D arrays. Prefix 'quad1d_' (the existing 'cc_'
% fixtures are covariance-conversion points, not Clenshaw-Curtis).
tclRoot = '/Users/nedonatelli/Documents/Local Repositories/matlab-tcl';
addpath(genpath(fullfile(tclRoot, 'Mathematical_Functions')));
outDir = '/Users/nedonatelli/Documents/Local Repositories/TCL/tests/fixtures/matlab';

% Clenshaw-Curtis: one CSV per n; row 1 = xi, row 2 = w.
for n = [2, 5, 8, 16, 33, 64]
    [xi, w] = ClenshawCurtisPoints1D(n);
    writematrix([xi; w.'], fullfile(outDir, sprintf('quad1d_cc_n%d.csv', n)));
end

% Fejer rules 1 and 2.
for n = [5, 16, 31]
    for rule = [1, 2]
        [xi, w] = FejerPoints1D(n, rule);
        writematrix([xi; w.'], ...
            fullfile(outDir, sprintf('quad1d_fejer_n%d_r%d.csv', n, rule)));
    end
end

% Conformal maps: (mapping, pointType, param) combinations; param=-1
% encodes "use the MATLAB default".
combos = [ ...
    0, 0, -1;  0, 1, -1;  0, 0, 7; ...
    1, 0, -1;  1, 1, -1;  1, 0, 2.0; ...
    2, 0, -1;  2, 0, 1.7; ...
    3, 0, -1;  3, 1, -1;  3, 0, 2.0 ...
];
n = 20;
for i = 1:size(combos, 1)
    mp = combos(i, 1); pt = combos(i, 2); pr = combos(i, 3);
    if pr < 0
        [xi, w] = conformMapQuadPts1D(n, mp, pt);
    else
        [xi, w] = conformMapQuadPts1D(n, mp, pt, pr);
    end
    if pr < 0; prTag = 'def'; else; prTag = strrep(sprintf('%g', pr), '.', 'p'); end
    writematrix([xi; w.'], fullfile(outDir, ...
        sprintf('quad1d_conform_m%d_p%d_%s.csv', mp, pt, prTag)));
end
fprintf('quadrature 1-D fixtures written\n');
